accounts/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from . import views as account_views
from profiles import views as profile_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', profile_views.SignUp.as_view(), name='signup'),
    path('profile/', profile_views.update_profile, name='profile'),
    path('my-favourites/', profile_views.FavouriteListView.as_view(), name='favourites'),
]

catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(r'', views.index, name='index'),
    path('my_ads/', views.UserAdsListView.as_view(), name='my_ads'),
    path('ads/', views.AdListView.as_view(), name='ads'),
    path('ads/<category>', views.AdListView.as_view(), name='ads'),
    # path('ad/<uuid:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/<uuid:ad_pk>', views.get_ad_detail, name='ad_detail'),
    path('ad/<uuid:ad_pk>/fav', views.update_fav, name='update_fav'),
    path('ad/<uuid:ad_pk>/request', views.add_request, name='request_ad'),
    path('ad/<uuid:ad_pk>/manage_requests', views.manage_requests, name='manage_requests'),
    path('ad/<uuid:ad_pk>/accept_request', views.accept_request, name='accept_request'),
    path('ad/<uuid:ad_pk>/cancel_request', views.cancel_request, name='cancel_request'),
    path('ad/<uuid:ad_pk>/update', views.AdUpdateView.as_view(), name='ad_update'),
    path('ad/<uuid:ad_pk>/delete', views.AdDeleteView.as_view(), name='ad_delete'),
    path('ad/create', views.AdCreate.as_view(), name='ad_create'),
]

rental_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
]

#Add URL maps to redirect the base URL to catalog application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/')),
]

# Static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
from django.contrib.auth import views as auth_views

urlpatterns += [
    path(r'^login/$', auth_views.login, name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include("accounts.urls", namespace="accounts")),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

''' URL mamgings for accounts
accounts/ login/ [name='login']
accounts/ logout/ [name='logout']
accounts/ password_change/ [name='password_change']
accounts/ password_change/done/ [name='password_change_done']
accounts/ password_reset/ [name='password_reset']
accounts/ password_reset/done/ [name='password_reset_done']
accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/ reset/done/ [name='password_reset_complete']
'''

catalog/models.py
from django.db import models
import uuid # To create unique ad instances
from django.urls import reverse #Used to generate URLs by reversing the URL patterns

from django.contrib.auth.models import User
from django.contrib import admin

from profiles.models import Profile

# Model representing category for tool (e.g. Moving, Gardening, Home Renovation, etc.)
class Category(models.Model):
    CATEGORY_CHOICES = (
        ('Home Renovation', 'Home Renovation'),
        ('Gardening', 'Gardening'),
        ('Power Tools', 'Power Tools'),
        ('Moving', 'Moving'),
        ('Garage', 'Garage'),
        ('Washroom', 'Washroom'),
        ('Kitchen', 'Kitchen'),
        ('Automobile', 'Automobile'),
        ('Other', 'Other'),
    )

    category_name = models.CharField(max_length=20, choices=CATEGORY_CHOICES, blank=True, default='Other', help_text="Choose a cateogry (e.g. Moving, Gardening etc.)", unique=True)

    category_img = models.ImageField(upload_to="catalog_images", blank=True, null=True,  default="catalog_images/no_img.png")

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name_plural = 'Categories'

# Model representing Ads that users can create
class Ad(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)

    renter = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=False, related_name='my_ads')

    ad_img = models.ImageField(upload_to="ad_images", blank=True, null=True,  default="ad_images/no_img.png")

    # Multiple people can request to borrow
    add_requestor = models.BooleanField(default=False)
    borrow_requests = models.ManyToManyField(Profile, blank=True,  related_name='borrow_requests')
    # Only one person can be borrower
    borrower = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name='borrower')

    location = models.CharField(max_length=100)
    # By design an Ad can only belong to one category. Later change to ManyToManyField to allow one ad to have multiple categories
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)

    LOAN_STATUS = (
        ('a', 'Available'),
        ('o', 'On loan'),
        ('c', 'Completed'),
    )
    loan_status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='a', help_text='Tool availability')

    loan_duration = models.IntegerField(help_text="Loan duration in days")
    price = models.DecimalField(max_digits=5, decimal_places=2)

    create_date = models.DateField(auto_now_add=True)
    update_date = models.DateField(auto_now=True)

    favourites = models.ManyToManyField(Profile, null=True, blank=True, related_name='favs')

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for the ad")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('ad_detail', args=[str(self.id)])

    def get_update_url(self):
        return reverse('ad_update', args=[str(self.id)])

    def get_delete_url(self):
        return reverse('ad_delete', args=[str(self.id)])

    def update_fav_url(self):
        return reverse('update_fav', args=[str(self.id)])

    def request_ad_url(self):
        return reverse('request_ad', args=[str(self.id)])

    def cancel_request(self):
        return reverse('cancel_request', args=[str(self.id)])

    def manage_requests(self):
        return reverse('manage_requests', args=[str(self.id)])

    def accept_request(self):
        return reverse('accept_request', kwargs={"ad_pk":str(self.id)})

catalog/forms.py
from django import forms
from django.forms import ModelForm, Textarea, CheckboxInput
from .models import Ad
from django.utils.translation import ugettext_lazy as _

catalog/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormMixin

from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Ad, Category
from profiles.models import Profile

from django.contrib.auth.decorators import login_required

def index(request):
    # Query all categories
    catagories = Category.objects.all()
    context = {"categories":catagories, 'num_cols':range(3), 'row_start':[0,3,6], 'row_end':[2,5,8]}
    return render(request,'index.html',context)

class AdListView(generic.ListView):
    model = Ad
    # Get only active ads
    def get_queryset(self):
        if self.kwargs:
            category = self.kwargs['category']
            return Ad.objects.filter(category__category_name__icontains=category).filter(loan_status='a')
        else:
            return Ad.objects.filter(loan_status='a')
        # return Ad.objects.filter(favourites=self.request.user.profile)

    def get_context_data(self, **kwargs):
        context = super(AdListView, self).get_context_data(**kwargs)
        if not self.request.user.id == None:
            fav_list = Ad.objects.filter(favourites=self.request.user.profile).values_list('title', flat=True)
            context['fav_list'] = fav_list
        return context

def catalog_list_view(request, cat):
    pass

class UserAdsListView(LoginRequiredMixin,generic.ListView):
    template_name ='catalog/ad_list_user.html'
    context_object_name = 'my_ads'

    def get_queryset(self):
        return Ad.objects.filter(renter=self.request.user.profile)

class AdCreate(LoginRequiredMixin, generic.CreateView):
    model = Ad
    fields = ['title', 'description', 'location', 'category', 'loan_duration', 'price', 'ad_img']

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.renter = self.request.user.profile
        self.object.save()
        return super().form_valid(form)

class AdUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Ad
    fields = ['title', 'description', 'location', 'category', 'loan_duration', 'price', 'ad_img']
    # To override default update page, uncomment line below
    template_name = "catalog/ad_update.html"

    # Override by default it is set to pk. Change this to ad_pk
    pk_url_kwarg = "ad_pk"

class AdDeleteView(DeleteView):
    model = Ad
    pk_url_kwarg = "ad_pk"
    success_url = reverse_lazy('my_ads')

def get_ad_detail(request, ad_pk):
    cur_ad = Ad.objects.filter(id=ad_pk).get()

    show_request = False
    show_unrequest = False

    if request.user.id == None:
        return render(request, 'catalog/ad_detail.html', {'ad':cur_ad})
    # Check if the current user is the creator of the ad
    if not (cur_ad.renter == request.user.profile):
        # Get list of users who requested this ad already
        request_list = Ad.objects.filter(borrow_requests=request.user.profile)
        # If current user requsted already, only show option to cancel request
        if cur_ad in request_list:
            show_unrequest = True
        else:
            show_request = True

    context = {'ad':cur_ad, 'show_request':show_request, 'show_unrequest':show_unrequest}
    return render(request, 'catalog/ad_detail.html', context)

def update_fav(request, ad_pk):
    cur_ad = get_object_or_404(Ad, id=ad_pk)
    if cur_ad:
        fav_list = Ad.objects.filter(favourites=request.user.profile)
        if cur_ad in fav_list:
            cur_ad.favourites.remove(request.user.profile)
        else:
            cur_ad.favourites.add(request.user.profile)

    return HttpResponseRedirect(reverse("ads"))

def add_request (request, ad_pk):
    cur_ad = get_object_or_404(Ad, id=ad_pk)
    if cur_ad:
        cur_ad.borrow_requests.add(request.user.profile)
    context = {'ad':cur_ad,}
    return HttpResponseRedirect(reverse('ad_detail', args=[ad_pk]))

def cancel_request (request, ad_pk):
    cur_ad = get_object_or_404(Ad, id=ad_pk)
    if cur_ad:
        cur_ad.borrow_requests.remove(request.user.profile)
    context = {'ad':cur_ad,}
    return HttpResponseRedirect(reverse('ad_detail', args=[ad_pk]))

def manage_requests (request, ad_pk):
    cur_ad = get_object_or_404(Ad, id=ad_pk)
    if request.method == 'POST':
        # Need the borroer id to set foreign key relation
        cur_ad.borrower_id = request.POST['requester_profile_id']
        cur_ad.loan_status = 'o'
        cur_ad.save()
        return HttpResponseRedirect(reverse('my_ads'))
    else:
        return render(request, 'catalog/manage_requests.html', {'ad':cur_ad})

def accept_request (request, ad_pk):
    return HttpResponseRedirect(reverse('my_ads'))

catalog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<style>
  body {
    padding-top: 65px;
  }
</style>

<head>

  {% block title %}<title>Rent It</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script  src="https://code.jquery.com/jquery-3.2.1.min.js"  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="  crossorigin="anonymous"></script>
  <link href="https://v4-alpha.getbootstrap.com/examples/album/album.css" rel="stylesheet">

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  {% include 'navbar.html' %}

  <div class="container">
      <div>
          {% block content %}
          {% endblock %}

          {% block styles %}
          {% endblock %}

          {% block scripts %}
          {% endblock %}
      </div>
  </div>

  </div>
</body>
</html>

catalog/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block styles %}
<style>
	.jumbotron {
		text-align: center;
	}

	.card {
	  float: center;
	  width: 25%;
	  padding: .75rem;
	  margin-bottom: 2rem;
	  border: 0;
	}
</style>
{% endblock %}

{% block content %}
<div class="col-sm-12">
	{% if not request.user.is_authenticated %}
		<h2>Welcome, login to start borrowing and renting items!</h2>
	{% else %}
		<h2>Hey {{ request.user.profile }}, have a look around!</h2>
	{% endif %}
	<div class="album text-muted">
		<div align="center">
			<!-- Use dicsort to order alphabetically -->
			{% for c in categories|dictsort:"category_name" %}
				{% if forloop.counter0 in row_start %}
					<div class="row">
				{% endif %}
							<div class="card">
								<a href="{% url 'ads' category=c %}">
									{% if c.category_img %}
								    <img src="{{ c.category_img.url }}" alt="no image uploaded"  height="150" class="img-rounded">
								  {% else %}
								    <p>No image uploaded</p>
								  {% endif %}
								</a>
								<h4>{{c.category_name}}</h4>
							</div>
				{% if forloop.counter0 in row_end %}
					</div>
				{% endif %}
			{% endfor %}
		</div>
	</div>
</div>
{% endblock %}

catalog/templates/navbar.html
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}">Rent It</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'ads' %}">Active Listings</a></li>

        {% if user.is_authenticated %}
          <li><a href="{% url 'ad_create' %}">Post Ad</a></li>
        {% endif %}

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            {% if request.user.is_authenticated %}
              Hey, {{ request.user.profile }}
            {% else %}
              Account
            {% endif %}
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            {% if not request.user.is_authenticated %}
              <li><a href="{% url 'login' %}">Login</a></li>
              <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
            {% else %}
              <li><a href="{% url 'accounts:profile' %}">My Profile</a></li>
              <li><a href="{% url 'my_ads' %}">My Ads</a></li>
              <li><a href="{% url 'accounts:favourites' %}">My Favourites</a></li>
              <li><a href="#">My Messages</a></li>
              <li><a href="{% url 'logout' %}">Logout</a></li>
            {% endif %}
          </ul>

        </li>

      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>