catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(r'', views.index, name='index'),
    path('my_ads/', views.UserAdsListView.as_view(), name='my_ads'),
    path('ads/', views.AdListView.as_view(), name='ads'),
    path('ads/<category>', views.AdListView.as_view(), name='ads'),
    # path('ad/<uuid:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/<uuid:ad_pk>', views.get_ad_detail, name='ad_detail'),
    path('ad/<uuid:ad_pk>/fav', views.update_fav, name='update_fav'),
    path('ad/<uuid:ad_pk>/request', views.add_request, name='request_ad'),
    path('ad/<uuid:ad_pk>/manage_requests', views.manage_requests, name='manage_requests'),
    path('ad/<uuid:ad_pk>/accept_request', views.accept_request, name='accept_request'),
    path('ad/<uuid:ad_pk>/cancel_request', views.cancel_request, name='cancel_request'),
    path('ad/<uuid:ad_pk>/update', views.AdUpdateView.as_view(), name='ad_update'),
    path('ad/<uuid:ad_pk>/delete', views.AdDeleteView.as_view(), name='ad_delete'),
    path('ad/create', views.AdCreate.as_view(), name='ad_create'),
]

rental_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
]

#Add URL maps to redirect the base URL to catalog application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/')),
]

# Static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
from django.contrib.auth import views as auth_views

urlpatterns += [
    path(r'^login/$', auth_views.login, name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include("accounts.urls", namespace="accounts")),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

''' URL mamgings for accounts
accounts/ login/ [name='login']
accounts/ logout/ [name='logout']
accounts/ password_change/ [name='password_change']
accounts/ password_change/done/ [name='password_change_done']
accounts/ password_reset/ [name='password_reset']
accounts/ password_reset/done/ [name='password_reset_done']
accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/ reset/done/ [name='password_reset_complete']
'''

catalog/models.py
from django.db import models
import uuid # To create unique ad instances
from django.urls import reverse #Used to generate URLs by reversing the URL patterns

from django.contrib.auth.models import User
from django.contrib import admin

from profiles.models import Profile

# Model representing category for tool (e.g. Moving, Gardening, Home Renovation, etc.)
class Category(models.Model):
    CATEGORY_CHOICES = (
        ('Home Renovation', 'Home Renovation'),
        ('Gardening', 'Gardening'),
        ('Power Tools', 'Power Tools'),
        ('Moving', 'Moving'),
        ('Garage', 'Garage'),
        ('Washroom', 'Washroom'),
        ('Kitchen', 'Kitchen'),
        ('Automobile', 'Automobile'),
        ('Other', 'Other'),
    )

    category_name = models.CharField(max_length=20, choices=CATEGORY_CHOICES, blank=True, default='Other', help_text="Choose a cateogry (e.g. Moving, Gardening etc.)", unique=True)

    category_img = models.ImageField(upload_to="catalog_images", blank=True, null=True,  default="catalog_images/no_img.png")

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name_plural = 'Categories'

# Model representing Ads that users can create
class Ad(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)

    renter = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=False, related_name='my_ads')

    ad_img = models.ImageField(upload_to="ad_images", blank=True, null=True,  default="ad_images/no_img.png")

    # Multiple people can request to borrow
    add_requestor = models.BooleanField(default=False)
    borrow_requests = models.ManyToManyField(Profile, blank=True,  related_name='borrow_requests')
    # Only one person can be borrower
    borrower = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name='borrower')

    location = models.CharField(max_length=100)
    # By design an Ad can only belong to one category. Later change to ManyToManyField to allow one ad to have multiple categories
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)

    LOAN_STATUS = (
        ('a', 'Available'),
        ('o', 'On loan'),
        ('c', 'Completed'),
    )
    loan_status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='a', help_text='Tool availability')

    loan_duration = models.IntegerField(help_text="Loan duration in days")
    price = models.DecimalField(max_digits=5, decimal_places=2)

    create_date = models.DateField(auto_now_add=True)
    update_date = models.DateField(auto_now=True)

    favourites = models.ManyToManyField(Profile, null=True, blank=True, related_name='favs')

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for the ad")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('ad_detail', args=[str(self.id)])

    def get_update_url(self):
        return reverse('ad_update', args=[str(self.id)])

    def get_delete_url(self):
        return reverse('ad_delete', args=[str(self.id)])

    def update_fav_url(self):
        return reverse('update_fav', args=[str(self.id)])

    def request_ad_url(self):
        return reverse('request_ad', args=[str(self.id)])

    def cancel_request(self):
        return reverse('cancel_request', args=[str(self.id)])

    def manage_requests(self):
        return reverse('manage_requests', args=[str(self.id)])

    def accept_request(self):
        return reverse('accept_request', kwargs={"ad_pk":str(self.id)})

catalog/forms.py
from django import forms
from django.forms import ModelForm, Textarea, CheckboxInput
from .models import Ad
from django.utils.translation import ugettext_lazy as _

catalog/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormMixin

from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Ad, Category
from profiles.models import Profile

from django.contrib.auth.decorators import login_required

def index(request):
    # Query all categories
    catagories = Category.objects.all()
    context = {"categories":catagories, 'num_cols':range(3), 'row_start':[0,3,6], 'row_end':[2,5,8]}
    return render(request,'index.html',context)

class AdListView(generic.ListView):
    model = Ad
    # Get only active ads
    def get_queryset(self):
        if self.kwargs:
            category = self.kwargs['category']
            return Ad.objects.filter(category__category_name__icontains=category).filter(loan_status='a')
        else:
            return Ad.objects.filter(loan_status='a')
        # return Ad.objects.filter(favourites=self.request.user.profile)

    def get_context_data(self, **kwargs):
        context = super(AdListView, self).get_context_data(**kwargs)
        if not self.request.user.id == None:
            fav_list = Ad.objects.filter(favourites=self.request.user.profile).values_list('title', flat=True)
            context['fav_list'] = fav_list
        return context

def catalog_list_view(request, cat):
    pass

class UserAdsListView(LoginRequiredMixin,generic.ListView):
    template_name ='catalog/ad_list_user.html'
    context_object_name = 'my_ads'

    def get_queryset(self):
        return Ad.objects.filter(renter=self.request.user.profile)

class AdCreate(LoginRequiredMixin, generic.CreateView):
    model = Ad
    fields = ['title', 'description', 'location', 'category', 'loan_duration', 'price', 'ad_img']

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.renter = self.request.user.profile
        self.object.save()
        return super().form_valid(form)

class AdUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Ad
    fields = ['title', 'description', 'location', 'category', 'loan_duration', 'price', 'ad_img']
    # To override default update page, uncomment line below
    template_name = "catalog/ad_update.html"

    # Override by default it is set to pk. Change this to ad_pk
    pk_url_kwarg = "ad_pk"

class AdDeleteView(DeleteView):
    model = Ad
    pk_url_kwarg = "ad_pk"
    success_url = reverse_lazy('my_ads')

def get_ad_detail(request, ad_pk):
    cur_ad = Ad.objects.filter(id=ad_pk).get()

    show_request = False
    show_unrequest = False

    if request.user.id == None:
        return render(request, 'catalog/ad_detail.html', {'ad':cur_ad})
    # Check if the current user is the creator of the ad
    if not (cur_ad.renter == request.user.profile):
        # Get list of users who requested this ad already
        request_list = Ad.objects.filter(borrow_requests=request.user.profile)
        # If current user requsted already, only show option to cancel request
        if cur_ad in request_list:
            show_unrequest = True
        else:
            show_request = True

    context = {'ad':cur_ad, 'show_request':show_request, 'show_unrequest':show_unrequest}
    return render(request, 'catalog/ad_detail.html', context)

def update_fav(request, ad_pk):
    cur_ad = get_object_or_404(Ad, id=ad_pk)
    if cur_ad:
        fav_list = Ad.objects.filter(favourites=request.user.profile)
        if cur_ad in fav_list:
            cur_ad.favourites.remove(request.user.profile)
        else:
            cur_ad.favourites.add(request.user.profile)

    return HttpResponseRedirect(reverse("ads"))

def add_request (request, ad_pk):
    cur_ad = get_object_or_404(Ad, id=ad_pk)
    if cur_ad:
        cur_ad.borrow_requests.add(request.user.profile)
    context = {'ad':cur_ad,}
    return HttpResponseRedirect(reverse('ad_detail', args=[ad_pk]))

def cancel_request (request, ad_pk):
    cur_ad = get_object_or_404(Ad, id=ad_pk)
    if cur_ad:
        cur_ad.borrow_requests.remove(request.user.profile)
    context = {'ad':cur_ad,}
    return HttpResponseRedirect(reverse('ad_detail', args=[ad_pk]))

def manage_requests (request, ad_pk):
    cur_ad = get_object_or_404(Ad, id=ad_pk)
    if request.method == 'POST':
        # Need the borroer id to set foreign key relation
        cur_ad.borrower_id = request.POST['requester_profile_id']
        cur_ad.loan_status = 'o'
        cur_ad.save()
        return HttpResponseRedirect(reverse('my_ads'))
    else:
        return render(request, 'catalog/manage_requests.html', {'ad':cur_ad})

def accept_request (request, ad_pk):
    return HttpResponseRedirect(reverse('my_ads'))

catalog/templates/catalog/accept_request.html
{% extends "base.html" %}

{% block content %}
<div class="col-sm-6 col-sm-offset-3">
  <form action="" method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete: <strong>{{object.title}}</strong></p>
    <input type="submit"  value="Confirm" class="btn btn-warning">
    <a href="{% url 'my_ads' %}" class="btn btn-default">Cancel</a>
  </form>
</div>
{% endblock %}

catalog/templates/catalog/ad_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="col-sm-6 col-sm-offset-3">
  <form action="" method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete: <strong>{{object.title}}</strong></p>
    <input type="submit"  value="Confirm" class="btn btn-warning">
    <a href="{% url 'my_ads' %}" class="btn btn-default">Cancel</a>
  </form>
</div>
{% endblock %}

catalog/templates/catalog/ad_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block styles %}
<style>
</style>
{% endblock %}

{% block content %}
  <h1>{{ad.title}}</h1>

  {% if ad.ad_img %}
    <img src="{{ ad.ad_img.url }}" alt="no image uploaded" width="240" class="img-rounded">
  {% else %}
    <p>No image uploaded</p>
  {% endif %}
  <p><strong>Description:</strong> {{ ad.description }} </a></p>
  <p><strong>Price:</strong> ${{ ad.price }} </a></p>

  {% if show_fav_form %}
  <form action="" method="post">
      {% csrf_token %}
      {{ fav_form|crispy }}
      <input class="btn btn-default" name="mashnoor_name" type="submit" value="Submit" />
  </form>
  {% endif %}
  {% if show_request %}
    <a href="{{ ad.request_ad_url }}">
      <button type="submit" class="btn btn-success">Request Item</button>
    </a>
  {% endif %}
  {% if show_unrequest %}
  <a href="{{ ad.cancel_request }}">
    <button type="submit" class="btn btn-danger">Cancel Request</button>
  </a>
  {% endif %}
  {% if not request.user.is_authenticated %}
    Login to be able to borrow this item
  {% endif %}
{% endblock %}

catalog/templates/catalog/ad_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>Create New Ad</h2>
<div class="col-sm-6">
<form action="" method="post" enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-success" type="submit" value="Submit" />
</form>
</div>
{% endblock %}

catalog/templates/catalog/ad_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block styles %}
<link rel="stylesheet" href="{% static 'catalog/table_styles.css' %}">
<style>
.fav_color {
  color: red;
}
.unfav_color {
  color: black;
}
</style>

{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'catalog/jquery-latest.js' %}"></script>
<script type="text/javascript" src="{% static 'catalog/jquery.tablesorter.js' %}"></script>

<script>
$(document).ready(function(){
  // Sort Ads by Date Posted initially
  $("#myTable").tablesorter( {sortList: [[3,1]]} );

  // $(".fav").click(function() {
  //   $(this).toggleClass("fav_color");
  // });
});

</script>
{% endblock %}

{% block content %}

<h1>Active Listings</h1>

{% if ad_list %}
<table id="myTable" class="table tablesorter">
<thead>
  <tr>
    <th>Ad</th>
    <th>Category</th>
    <th>Add to Favourites</th>
    <th>Price</th>
    <th>Location</th>
    <th>Date Posted</th>
  </tr>
</thead>
<tbody>
  {% for ad in ad_list %}
  <tr>
    <td><a href="{{ ad.get_absolute_url }}">{{ ad.title }}</a></td>
    <td>{{ad.category}}</td>
    <td>
      {% if request.user.is_authenticated %}
      <a href="{{ ad.update_fav_url }}">
        <span type="button" class="{% if ad.title in fav_list %} fav_color {% else %} unfav_color {% endif %}glyphicon glyphicon-heart"></span>
      </a>
      {% else %}
      Login to favourite
      {% endif %}
    </td>
    <td>${{ad.price}}</td>
    <td >{{ad.location}}</td>
    <td>{{ad.create_date}}</td>
  </tr>
  {% endfor %}
</tbody>
</table>
{% else %}
  <p>There are no active ads sorry. Please post one! :)</p>
{% endif %}

{% endblock %}

catalog/templates/catalog/ad_list_user.html
{% extends "base.html" %}

{% block styles %}
<style>
.red_color {
  color: red;
}
</style>
{% endblock %}


{% block content %}

<div class="col-sm-6">
  <h2>My Active Ads</h2>
  {% if my_ads %}
  <table class="table">
  <thead>
    <tr>
      <th><strong>Ad</strong></th>
      <th><strong>Loan Status</strong></th>
      <th><strong>Delete</strong></th>
      <th><strong>Borrow Requests</strong></th>
    </tr>
  </thead>
  <tbody>
    {% for ad in my_ads %}
    <tr>
      {% if ad.loan_status == 'a' %}
        <td><a href="{{ ad.get_update_url }}">{{ ad.title }}</a></td>
        <td>{{ ad.get_loan_status_display }}</td>
        <td><a href="{{ ad.get_delete_url }}"><span type="button" class="red_color glyphicon glyphicon-remove"></span></a></td>
        <td><a href="{{ ad.manage_requests }}">{{ad.borrow_requests.all.count}}</a></td>
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
  </table>
  {% else %}
    <p>You do not have any ads</p>
  {% endif %}

  <h2>My On Loan and Completed Ads</h2>
  {% if my_ads %}
  <table class="table">
  <thead>
    <tr>
      <th><strong>Ad</strong></th>
      <th><strong>Loan Status</strong></th>
      <th><strong>Delete</strong></th>
      <th>Loaned To</th>
    </tr>
  </thead>
  <tbody>
    {% for ad in my_ads %}
    <tr>
      {% if not ad.loan_status == 'a' %}
        <td><a href="{{ ad.get_update_url }}">{{ ad.title }}</a></td>
        <td>{{ ad.get_loan_status_display }}</td>
        <td><a href="{{ ad.get_delete_url }}"><span type="button" class="red_color glyphicon glyphicon-remove"></span></a></td>
        {% if ad.borrower %}
          <td>{{ad.borrower}}</td>
        {% else %}
          <td>No one</td>
        {% endif %}
      {% endif %}
    </tr>
    {% endfor %}
    {% else %}
      <p>You do not have any ads</p>
    {% endif %}
  </tbody>
  </table>

</div>

{% endblock %}

catalog/templates/catalog/ad_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>Update Ad for: {{object.title}}</h2>
<div class="col-sm-6">
<form action="" method="post" enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
    {{ form|crispy }}
    </table>
    <input class="btn btn-success" type="submit" value="Submit" />
</form>
</div>
{% endblock %}

catalog/templates/catalog/manage_requests.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block styles %}
<style>
.green_color {
  color: #008000;
}
</style>
{% endblock %}

{% block content %}
<div class="col-sm-4">
<h2>Requests for: {{ad.title}}</h2>
{% if ad.borrow_requests.count == 0  %}
  <p>No one wants to borrow this. Sorry :( </p>
{% else %}
  <table class="table">
    <thead>
      <tr>
        <th><strong>Requester</strong></th>
        <th><strong>Accept Request</strong></th>
      </tr>
    </thead>
    <tbody>
      {% for requester in ad.borrow_requests.all %}
        <tr>
            <td>{{requester}}</td>
            <td>
              <form action="" method="POST">
                {% csrf_token %}
                  <button onclick="return confirm('Are you you want to accept this request?')" class="btn btn-success" name="requester_profile_id" value="{{requester.id}}">Accept</button>
              </form>
            </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endif %}
<div class="col-sm-4">
{% endblock %}


<!--             <td><a href="{{ ad.accept_request }}"><span onclick="return confirm('Are you sure?')" class="green_color glyphicon glyphicon-ok"></span></a></td>  -->